#!/usr/bin/env python
# -*- coding: utf-8 -*-

#
# Copyright 2009 Christoph Böhme
#
# This file is part of Openstreetbugs.
#
# Openstreetbugs is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Openstreetbugs is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Openstreetbugs.  If not, see <http://www.gnu.org/licenses/>.
#

import MySQLdb
import cgi
import re


import db_config # DATABASE CONFIGURATION


def main():
	print "Content-type: text/html\n"
	form = cgi.FieldStorage()

	values = {}
	values["lat"] = form.getfirst("lat", "")
	values["lon"] = form.getfirst("lon", "")
	values["text"] = form.getfirst("text", "")

	# Check that parameters have a valid format:
	coord_exp = re.compile(r"^-?\d{1,3}(\.\d+)?$")
	if not coord_exp.match(values["lat"]) or not (-180 <= float(values["lat"]) and float(values["lat"]) <= 180):
		print "invalid or missing lat"
		return
	if not coord_exp.match(values["lon"]) or not (-180 <= float(values["lon"]) and float(values["lon"]) <= 180):
		print "invalid or missing lon"
		return
	if values["text"].strip() == "" or not re.match(r"^[^\x00-\x1f]*$", values["text"]):
		print "invalid or missing text"
		return

	values["text"] = cgi.escape(values["text"], True)

	conn = MySQLdb.connect(db_config.host, user=db_config.user, passwd=db_config.password, db=db_config.dbname)
	curs = conn.cursor()
	curs.execute("INSERT INTO bugs SET lat = %(lat)s, lon = %(lon)s, text = %(text)s, type = 0, last_changed = NOW()", values)
	conn.commit()

	print "bug added";

main()
