#!/usr/bin/env python
# -*- coding: utf-8 -*-

#
# Copyright 2009 Christoph Böhme
#
# This file is part of Openstreetbugs.
#
# Openstreetbugs is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Openstreetbugs is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Openstreetbugs.  If not, see <http://www.gnu.org/licenses/>.
#

import MySQLdb
import cgi
import re
from datetime import datetime
from pytz import timezone


import db_config # DATABASE CONFIGURATION


def main():
	form = cgi.FieldStorage()

	values = {}
	values["id"] = form.getfirst("id", "")
	values["text"] = form.getfirst("text", "")

	output_format = form.getfirst("format", "")
	output_format_js = re.match("js", output_format)

	if output_format_js:
		print "Content-type: text/javascript; charset=UTF-8\n"
	else:
		print "Content-type: text/html\n"

	# Check that parameters have a valid format:
	if not re.match(r"^\d+$", values["id"]):
		if output_format_js:
			print "osbResponse(\"invalid or missing id\");"
		else:
			print "invalid or missing id"
		return
	if values["text"].strip() == "" or not re.match(r"^[^\x00-\x1f]*$", values["text"]):
		if output_format_js:
			print "osbResponse(\"invalid or missing text\");"
		else:
			print "invalid or missing text"
		return

	values["text"] = cgi.escape(values["text"], True)

	timestamp_exp = re.compile(r".*[0-9]{2}:[0-9]{2}:[0-9]{2}.*")
	if not timestamp_exp.match(values["text"]):
		values["text"] = values["text"][:-1] # strip last character "]"
		values["text"] = values["text"] + ", " + datetime.strftime(datetime.now(timezone("Europe/Berlin")),"%Y-%m-%d %H:%M:%S %Z") + "]"

	conn = MySQLdb.connect(db_config.host, user=db_config.user, passwd=db_config.password, db=db_config.dbname, 
			charset = "utf8", use_unicode = True)
	curs = conn.cursor()
	curs.execute("UPDATE bugs SET text = CONCAT(text, '<hr />', %(text)s), last_changed = NOW() WHERE id = %(id)s", values)
	conn.commit()

	if output_format_js:
		print "osbResponse();"
	else:
		print "comment added"

main()
