#!/usr/bin/env python
# -*- coding: utf-8 -*-

#
# Copyright 2009 Christoph Böhme, Mitja Kleider
#
# This file is part of Openstreetbugs.
#
# Openstreetbugs is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Openstreetbugs is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Openstreetbugs.  If not, see <http://www.gnu.org/licenses/>.
#

import MySQLdb
import cgi
import re

import db_config # DATABASE CONFIGURATION

def main():
	print "Content-type: text/javascript; Charset=UTF-8\n"
	form = cgi.FieldStorage()

	values = {}
	values["b"] = form.getfirst("b", "")
	values["t"] = form.getfirst("t", "")
	values["l"] = form.getfirst("l", "")
	values["r"] = form.getfirst("r", "")

	# Check that parameters have a valid format:
	coord_exp = re.compile(r"^-?\d{1,3}(\.\d+)?$")
	for k, v in values.iteritems():
		if not coord_exp.match(v):
			print "/*invalid or missing %s*/" % k
			return
		else:
			values[k] = float(v)
	
	conn = MySQLdb.connect(db_config.host, user=db_config.user, passwd=db_config.password, db=db_config.dbname,
			       charset = "utf8", use_unicode = True)
	curs = conn.cursor()

	curs.execute("SELECT * FROM bugs WHERE %(b)s <= lat and lat <= %(t)s and %(l)s <= lon and lon <= %(r)s AND (type = 0 OR TIMESTAMPDIFF(DAY, `last_changed`, NOW()) <= 7) ORDER BY last_changed DESC LIMIT 100", values)
	for c in curs:
		print "putAJAXMarker(%i, %f, %f, '%s', %i);" % (c[0], c[1], c[2], c[3].replace("'", "\\'"), c[4])

main()
