#!/usr/bin/env python
# -*- coding: utf-8 -*-

#
# Copyright 2009 Christoph Böhme, Mitja Kleider
#
# This file is part of Openstreetbugs.
#
# Openstreetbugs is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Openstreetbugs is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Openstreetbugs.  If not, see <http://www.gnu.org/licenses/>.
#

import MySQLdb
import cgi
import re

import db_config # DATABASE CONFIGURATION

def main():
	server_uri = "http://openstreetbugs.schokokeks.org/"
	api_uri = server_uri+"api/0.1/"

	print "Content-type: application/rss+xml\n"
	
	print """<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0" xmlns:geo="http://www.w3.org/2003/01/geo/wgs84_pos#" xmlns:dc="http://purl.org/dc/elements/1.1/">
<channel>
	<title>OpenStreetBugs</title>
	<link>"""+server_uri+"""</link>
	<description>last modified bugs in selected area</description>"""
	
	form = cgi.FieldStorage()
	values = {}
	values["b"] = form.getfirst("b", "")
	values["t"] = form.getfirst("t", "")
	values["l"] = form.getfirst("l", "")
	values["r"] = form.getfirst("r", "")
	
	# check whether key "open" exists
	if form.has_key('open'): # return only open bugs
		filter = "type = 0 AND "
	else:
		filter = ""
	
	# Check that parameters have a valid format:
	coord_exp = re.compile(r"^-?\d{1,3}(\.\d+)?$")
	for k, v in values.iteritems():
		if not coord_exp.match(v):
			print "<!-- invalid or missing %s -->" % k
			return
		else:
			values[k] = float(v)
	
	conn = MySQLdb.connect(db_config.host, user=db_config.user, passwd=db_config.password, db=db_config.dbname)
	curs = conn.cursor()
	querystr = "SELECT id, lon, lat, text, type, last_changed, nearby_place FROM bugs WHERE "+filter+"%(b)s <= lat and lat <= %(t)s and %(l)s <= lon and lon <= %(r)s ORDER BY last_changed DESC" % values
	limit = "10"
	querystr += " LIMIT %s" % limit
	curs.execute(querystr)
	for c in curs:
		if c[4] == 1:
			type = "closed bug"
		elif c[3].find("<hr />") != -1:
                        type = "new comment"
		else:
			type = "new bug"

		pubDate = c[5].strftime("%a, %d %b %Y %H:%M:%S GMT")
		desc = c[3].replace("<hr />"," | ")
		print "<item><title>%s (near %s)</title><description>%s</description><link>%s?lat=%s&amp;lon=%s&amp;zoom=18</link><guid>%srssitem?id=%s</guid><pubDate>%s</pubDate><geo:lat>%s</geo:lat><geo:long>%s</geo:long></item>" % (type, c[6].encode("utf-8"), desc, server_uri, c[2], c[1], api_uri, c[0], pubDate, c[2], c[1])
	print "</channel></rss>"

main()
